id = "matlab"
name = "MATLAB"
description = "MATLAB support for Zed"
version = "0.1.0"
schema_version = 1
authors = [
  "Mark Shui Hu <watermarkhu@gmail.com>"
]
repository = "https://github.com/watermarkhu/zed-matlab"

[grammars.matlab]
repository = "https://github.com/acristoffers/tree-sitter-matlab"
rev = "1bccabdbd420a9c3c3f96f36d7f9e65b3d9c88ef"

[language_servers.matlab-language-server]
name = "MATLAB LSP"
languages = ["MATLAB"]
